spring.application.name=HomeworkORM
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Отключаем стандартную инициализацию schema.sql/data.sql
spring.sql.init.mode=never

# Настройки Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Настройки Hibernate (ddl-auto=validate, так как схему создает Liquibase)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
